### ISSUE TITLE
Script only downloads files with extension JPG

### ISSUE THREAD

**Issue by pandages** [MrAusnadian/misc-powershell#2]
By design, this script only downloads files with names like *.JPG.  Should a file be named *.JPEG it will not be processed.  PNG files will also not be processed.

I'm working on a way to fix that.

**Comment by pandages** [comment]
The solution is an update to the regex used in the Where-Object on line 12.  I have a version that should work, testing it now before submitting a pull request.

`| ? { $_ -match "\.(jpe?)|(pn)g$" }`

**Comment by wi-ry** [comment]
Fixed in linked PR. Thanks @pandages!!
