### ISSUE TITLE
Only searches 1 subreddit at a time

### ISSUE THREAD

**Issue by pandages** [MrAusnadian/misc-powershell#5]
With some tweaks to the code, I think this script could check multiple subreddits.  I feel like that would be smart, especially when combined with making the naming of files be human-readable, at that would catch crossposts and eliminate duplicates.

**Comment by pandages** [comment]
I've reworked much of this code to be able to use the Reddit Thread titles as filenames.  I made sure to remove any characters that would be Invalid within a filename.

I'll be updating my fork of this codebase accordingly, along with increasing the amount of documentation.

**Comment by pandages** [comment]
I have an idea how / where to iterate through the subreddits, but I'm trying to figure out how you'd pass multiple in.  I guess you could change the input parameter into an array.  but it might be better to have a sidecar .TXT file and have people put 1 subreddit per line.  Powershell can import that really well, and would be trivial to iterate through.

I'll put together a version with that tomorrow.  Let me know if you think it's a bad idea, maybe I can come up with something else.

**Comment by wi-ry** [comment]
This was pretty simple, so I implemented it
