### ISSUE TITLE
Checks dimensions of files once downloaded, rather than within the JSON prior to download

### ISSUE THREAD

**Issue by pandages** [MrAusnadian/misc-powershell#6]
There's a significant block of code in this script which appears to be present specifically to check that files are no smaller than the specified minimum Height and Width parameters.

The Height and Width values of the images are contained within the JSON:

data.children.data.preview.images.source.height
data.children.data.preview.images.source.width

We can filter out files that are below the minimum specified by the input parameters, just have to rework a bit of the code.  I'll see what I can do.

**Comment by wi-ry** [comment]
Awesome suggestion! Check the PR I created :)
